-- Row Level Security (RLS) 활성화

-- 모든 테이블에 RLS 활성화
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE voters ENABLE ROW LEVEL SECURITY;
ALTER TABLE date_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekday_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE final_appointments ENABLE ROW LEVEL SECURITY;
